language: node_js
node_js:
 - stable
script:
 - npm run coverage
branches:
   only:
   - development
notifications:
    email:
      recipients:
        - siobhanomahony1994@hotmail.com
      on_success: never        # default: change
      on_failure: always       # default: always